PRODUCT_COPY_FILES += \
	$(CUR_PATH)/Firmware/TV/rtl8821c_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821c_config \
	$(CUR_PATH)/Firmware/TV/rtl8821c_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821c_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8821c_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821c_fw \
	$(CUR_PATH)/Firmware/TV/rtl8821cs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821cs_config \
	$(CUR_PATH)/Firmware/TV/rtl8821cs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821cs_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8821cs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8821cs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8822c_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822c_config \
	$(CUR_PATH)/Firmware/TV/rtl8822c_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822c_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8822c_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822c_fw \
	$(CUR_PATH)/Firmware/TV/rtl8822cs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822cs_config \
	$(CUR_PATH)/Firmware/TV/rtl8822cs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822cs_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8822cs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822cs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8761b_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761b_config \
	$(CUR_PATH)/Firmware/TV/rtl8761b_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761b_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8761b_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761b_fw \
	$(CUR_PATH)/Firmware/TV/rtl8761bt_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761bt_config \
	$(CUR_PATH)/Firmware/TV/rtl8761bt_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761bt_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8761bt_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8761bt_fw \
	$(CUR_PATH)/Firmware/TV/rtl8725a_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8725a_config \
	$(CUR_PATH)/Firmware/TV/rtl8725a_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8725a_fw \
	$(CUR_PATH)/Firmware/TV/rtl8733b_8723f_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733b_8723f_config \
	$(CUR_PATH)/Firmware/TV/rtl8733b_8723f_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733b_8723f_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8733b_8723f_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733b_8723f_fw \
	$(CUR_PATH)/Firmware/TV/rtl8733bs_8723fs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733bs_8723fs_config \
	$(CUR_PATH)/Firmware/TV/rtl8733bs_8723fs_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733bs_8723fs_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8733bs_8723fs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8733bs_8723fs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852as_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852as_config \
	$(CUR_PATH)/Firmware/TV/rtl8852as_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852as_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8852as_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852as_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852au_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852au_config \
	$(CUR_PATH)/Firmware/TV/rtl8852au_config_vendor:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852au_config_vendor \
	$(CUR_PATH)/Firmware/TV/rtl8852au_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852au_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852bps_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bps_config \
	$(CUR_PATH)/Firmware/TV/rtl8852bps_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bps_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852bs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bs_config \
	$(CUR_PATH)/Firmware/TV/rtl8852bs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852bu_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bu_config \
	$(CUR_PATH)/Firmware/TV/rtl8852bu_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852bu_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852cu_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852cu_config \
	$(CUR_PATH)/Firmware/TV/rtl8852cu_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852cu_fw \
	$(CUR_PATH)/Firmware/TV/rtl8852cs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852cs_config \
	$(CUR_PATH)/Firmware/TV/rtl8852cs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8852cs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8822es_8822cs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822es_8822cs_config \
	$(CUR_PATH)/Firmware/TV/rtl8822es_8822cs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822es_8822cs_fw \
	$(CUR_PATH)/Firmware/TV/rtl8822e_8822c_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822e_8822c_config \
	$(CUR_PATH)/Firmware/TV/rtl8822e_8822c_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8822e_8822c_fw \
	$(CUR_PATH)/Firmware/TV/rtl8851bu_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8851bu_config \
	$(CUR_PATH)/Firmware/TV/rtl8851bu_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8851bu_fw \
	$(CUR_PATH)/Firmware/TV/rtl8851bs_config:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8851bs_config \
	$(CUR_PATH)/Firmware/TV/rtl8851bs_fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rtl8851bs_fw \
